version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo:27017/fhirp2p
      - WEBTORRENT_TRACKERS=wss://tracker.openwebtorrent.com,wss://tracker.btorrent.xyz,wss://tracker.fastcast.nz
      - WEBTORRENT_DHT=true
      - WEBTORRENT_WEBSEEDS=true
      - FHIR_VALIDATION_LEVEL=warning
      - FHIR_DEFAULT_FORMAT=json
      - UI_THEME=light
      - UI_DENSITY=comfortable
      - STORAGE_TEMP_PATH=/data/fhir-torrents
      - DEBUG=true
    volumes:
      - fhir-data:/data/fhir-torrents
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    restart: unless-stopped

volumes:
  mongodb-data:
  fhir-data: